name: Notify users based on issue labels

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: adamtharani/issue-label-notification-action@master
        with:
          recipients: |
            help wanted=@adamtharani @nmsean
            documentation=@adamtharani
            bug=@adamtharani
